name: "Test"

# actions-up-ignore-file

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/test.yaml"
      - "action.yml"
      - "src/update-formula.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  test1:
    name: "Test 1"
    if: ${{ !contains(github.event.head_commit.message, '#notest') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          url: "https://example.com/toml_run-0.0.${{ github.run_number }}.tar.gz"
          #url: "https://github.com/cssnr/vitepress-plugin-contributors/releases/download/0.0.5/get-contributors.js"
          sha256: "abc123${{ github.run_number }}"
          #version: ${{ github.ref_name }}
          repo: smashedr/homebrew-test
          formula: toml-run.rb
          message: Bump toml-run.rb to 0.${{ github.run_attempt }}.${{ github.run_number }}
          #branch: master
          #create_branch: true
          token: ${{ secrets.HOMEBREW_TEST }}
          #app_id: 146360
          #app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          #commit: false
          pull: true

      - name: "Validate Outputs"
        uses: cssnr/validate-outputs-action@master
        with:
          outputs: ${{ toJSON(steps.test.outputs) }}
          data: |
            formula: toml-run.rb
            message: Bump toml-run.rb to 0.${{ github.run_attempt }}.${{ github.run_number }}
            #branch: master
            sha256: "abc123${{ github.run_number }}"
            #sha256: 9309a179f2440f0ea576e31031e87f2c9eda26bc72f5eb5f9924463e75a06ec1
            sha:

  #test2:
  #  name: "Test 2"
  #  runs-on: ubuntu-latest
  #  timeout-minutes: 5
  #  permissions:
  #    contents: write
  #
  #  steps:
  #    - name: "Checkout"
  #      uses: actions/checkout@v6
  #
  #    - name: "Test Local Action"
  #      id: test
  #      uses: ./
  #      with:
  #        url: "https://github.com/cssnr/vitepress-plugin-contributors/releases/download/0.0.5/get-contributors.js"
  #        #sha256: "abc123${{ github.run_number }}"
  #        #version: ${{ github.ref_name }}
  #        repo: smashedr/homebrew-test
  #        formula: toml-run.rb
  #        #message: Bump toml-run.rb to 0.${{ github.run_attempt }}.${{ github.run_number }}
  #        #branch: master
  #        commit: false
  #
  #    - name: "Validate Outputs"
  #      uses: cssnr/validate-outputs-action@master
  #      with:
  #        outputs: ${{ toJSON(steps.test.outputs) }}
  #        data: |
  #          formula: toml-run.rb
  #          message: Bump toml-run.rb to 0.${{ github.run_attempt }}.${{ github.run_number }}
  #          branch: master
  #          sha256: 9309a179f2440f0ea576e31031e87f2c9eda26bc72f5eb5f9924463e75a06ec1
