name: "Test"

# actions-up-ignore-file

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/test.yaml"
      - "action.yml"
      - "src/update-formula.sh"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

env:
  repository: smashedr/homebrew-test

jobs:
  test1:
    name: "Test 1"
    if: ${{ !contains(github.event.head_commit.message, '#notest') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Cleanup PR"
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_TEST }}
        run: |
          number="$(gh pr list \
            --repo "${{ env.repository }}" --json number \
            --template '{{if gt (len .) 0}}{{(index . 0).number}}{{end}}' \
          )"
          if [ -n "${number}" ];then
            echo "Closing Pull Request: ${number}"
            gh pr close --repo "${{ env.repository }}" "${number}"
            echo "Waiting 3 Seconds..."
            sleep 3
          else
            echo "No PR's found: ${{ github.server_url }}/${{ env.repository }}/pulls"
          fi

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          url: "https://example.com/toml_run-0.0.${{ github.run_number }}.tar.gz"
          sha256: "abc123${{ github.run_number }}"
          #version: ${{ github.ref_name }}
          repo: ${{ env.repository }}
          formula: toml-run.rb
          message: üç∫ Bump toml-run.rb to 0.${{ github.run_attempt }}.${{ github.run_number }}
          #branch: master
          #create_branch: true
          #token: ${{ secrets.HOMEBREW_TEST }}
          app_id: 146360
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          #commit: false
          pull: true

      #- name: "Add PR Comment"
      #  if: ${{ github.event_name == 'pull_request' }}
      #  continue-on-error: true
      #  env:
      #    GH_TOKEN: ${{ secrets.HOMEBREW_TEST }}
      #  run: |
      #    gh pr comment ${{ fromJSON(steps.test.outputs.pull).number }} -b \
      #    "PR: ${{ fromJSON(steps.test.outputs.pull).html_url }}"

      - name: "Validate Outputs"
        uses: cssnr/validate-outputs-action@master
        with:
          outputs: ${{ toJSON(steps.test.outputs) }}
          data: |
            formula: toml-run.rb
            message: üç∫ Bump toml-run.rb to 0.${{ github.run_attempt }}.${{ github.run_number }}
            branch:
            sha256: "abc123${{ github.run_number }}"
            sha:
            pull:

  test2:
    name: "Test 2"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          url: "https://github.com/cssnr/vitepress-plugin-contributors/releases/download/0.0.5/get-contributors.js"
          repo: ${{ env.repository }}
          formula: npmstat.rb
          commit: false

      - name: "Validate Outputs"
        uses: cssnr/validate-outputs-action@master
        with:
          outputs: ${{ toJSON(steps.test.outputs) }}
          data: |
            formula: npmstat.rb
            message: Bump npmstat.rb
            branch: master
            sha256: 9309a179f2440f0ea576e31031e87f2c9eda26bc72f5eb5f9924463e75a06ec1
